### ISSUE TITLE
.htaccess issue!

### ISSUE THREAD

**Issue by iphoneihelper** [sctigercat1/Cydia-UDID-Protected-Repo-PHP#15]
I just want to make sure that uploaded deb show up deb folder and I successfully added repo. Does it mean that initial setup perfect? later on I did try to download package.. and this happen. HTTP/1.1 404 Not Found. I have noticed that HTTP/1.0 error is mention in repo.php and replies.php so anything wrong with my repo structure.

Probably there is a easy fix for this or some silly mistake(s) but after trying three different UDID method from different people, now I am done so need your help to finish the last step. Kindly give me your email or Twitter.

BTW thanks for this. Appreciate your effort.

**Comment by sctigercat1** [comment]
Well, there could be a few things here:

1. The .deb file isn't being uploaded at all by the script; if so, you may want to make sure all the permissions are correctly setup.
2. Something happened in the control file setup/package save and the filename attribute of the control file is invalid. Check the latest control file and make sure the deb file actually exists at the location it says it does.
3. The deb file was incorrectly uploaded and was aborted by the server.
4. Also, note that the 404 notices found in repo.php and repofiles.php are just there if I choose to use that specific error code in the future. At this point, they have no purpose since I never call the error script as that code.

**Comment by iphoneihelper** [comment]
Ok that problem is solve. deb/FileName.deb was wrong.

I have no UDID added and try to download package and it starts so something still wrong.

**Comment by sctigercat1** [comment]
Well, for the UDID protection, first check to make sure you didn't select user level 0 as the permissions for your deb file. This user level is the "guest" level which is visible to everyone. To do so, visit the allFiles.php page and select your deb package from the list of currently installed packages.

Secondly, all file permissions and such are stored in the package_groups.json file. Make sure that file is writable by the server in order to successfully save the details of your deb.

I'd assume it's one of the two above as you said the deb was able to successfully install, just not be UDID restricted.

**Comment by iphoneihelper** [comment]
Permission level was not 0. 

I have re-uploaded deb file and its was perfectly done. I have assigned Level 2 to deb then I directly try to download package. I did not have added any UDID so it should not download, right? I can download the file. As I have mentioned earlier that the downloading page takes some time (Must be php process going on) and starts download.

I have double check the all the information after and before adding UDID as well. package_groups.json, approved_udids_2 files holding the correct information. Package_groups.jason stores deb filename and permission information while UDID stores the details of ID, name and level.

UDID permission and Deb permission has to be same in order to download package, right? First of all I want to check it without adding UDID so it wouldn't download anything unless permission level 0. (Thats not my case)

I hope the information I gave you is enough to understand what I am dealing with right now.

Twitter :- @iesight

**Comment by iphoneihelper** [comment]
What should I do now?

**Comment by sctigercat1** [comment]
When you said the package would download without checking the UDID, where does it download from? Directly from the debs folder or from the repo.php file?

This might be an issue with the .htaccess (it redirects all .deb requests in /debs to a file called repo.php which in turn checks if you have permission to download the package).

**Comment by iphoneihelper** [comment]
I have check the public_html/.htaccess file. RewriteBase /repo/ is present. link of my repo is like this :- http://myrepo.com/repo

Sir I did try to download file from web by http://myrepo.com/repo/debs/file.deb and its downloading so .htaccess is not working, right? Well that was my initial issue with other people's method and I have placed one html file to check whether .htaccess working or not. It was successfully redirect to website I have mentioned in .htaccess. Do I miss something else? Does .htaccess require other thing? My PHP version is 5.4.37.

Package file should be debs/myfile.deb, right? You have mentioned in the README that package and release are redirect. If I have no mention of those file in .htaccess. How do they redirect? Does .htaccess require the mention of release and package?
File size is 1.5 MB.
I have Package.gz present in /public_html/repo/
All the files you have mentioned are set to 777 and rest are 775.

Sir I guess I inch close to this thing don't know what is really happening but your help certainly help me to get through. I appreciate your time. I don't want to snatch your quality time but if possible via email or twitter, we can solve this issue as soon as possible.
for in case ...
paarthdesai@me.com
@iesight

**Comment by sctigercat1** [comment]
I'll be honest -- it seems like it should be working, so far I can't find much wrong with what you've described.

Firstly, though, let me make sure this is the directory structure:
public_html/.htaccess   <--- Note, this file is the .htaccess in the root of this github repo. You have to move this htaccess file out of the repo folder to the root of your site, if you haven't done so already. (This is because it is set to redirect public_html/repo/debs/Filename.deb to public_html/repo/repo.php?file=Filename; if the htaccess was in the /repo/ folder it would try to redirect /repo/repo/debs/ to /repo/repo/repo.php because it is set to redirect the /root/ folder from the .htaccess's initial location [which we want to be in the root, or public_html in your case].)
public_html/Admin.php
public_html/debs/Filename.deb
public_html/ChangeFile.php

And so on...

Also, to answer your second question, the last two lines of the htaccess do the redirecting:


RewriteRule ^(Packages|Release)(.bz2|.gz|.xz|.lzma|.lz)?$ repofiles.php?request=%{REQUEST_FILENAME}
RewriteRule ^debs/(.*)\.deb$ repo.php?file=$1 [QSA]

The first one does the package and release files whereas the second is the one that actually redirects the .deb files.

**Comment by iphoneihelper** [comment]
![screenshot 2015-03-27 22 23 34](https://cloud.githubusercontent.com/assets/10158017/6872537/fa7bf9f0-d4cf-11e4-8142-dfa7d768f559.png)

I have all your files in public_html/repo/ folder along with package package.gz and release files. I have double checked that .htaccess was in the public_html.

Current package permission level to 3 and there is no UDID added.

**Comment by sctigercat1** [comment]
Oh wow, the htaccess file isn't written correctly it seems (at least, it appears so haha).

Would you mind trying this?

1. Open the .htaccess file and change the line
RewriteBase /repo/
To:
RewriteBase /

Then, move the htaccess file into the repo sub directory. The file (repo.php) might not be able to be found by the htaccess since it's not in the directory with it.

Also, I would assume that by going to http://www.mywebsite.com/repo/repo.php?file=fileidentifier it wouldn't download it? Or does that link allow for the file to download also?

**Comment by iphoneihelper** [comment]
1) Ok so I did those changes and move the file to repo directory. There is no .htaccess file in public_html now.

2) Also by  http://www.mywebsite.com/repo/repo.php?file=com.file.identifier redirect to Personal Resrticted Website. I mean repo.php.  Its should be the build identifier at last in above link, right?

Strange thing happen. I am not able to add my repo on iPhone. Did not find repository.

**Comment by iphoneihelper** [comment]
I did try to remove repo .htaccess file and put into public_html with /repo/ and repo starts working.

After that I did remove .htaccess file from public_html and when I added repo. It was completely different. My logo is appearing and proper site name in our case My Personal Repo. Repo name appear as my website link before. Its look more perfect now. At the bottom there is download counter. Package.bz2 is now generating and appear in repo folder.

![screenshot 2015-03-28 10 06 11](https://cloud.githubusercontent.com/assets/10158017/6879816/549cfd50-d532-11e4-9a45-df741732779b.png)

BUT STILL THAT UDID THING IS NOT WORKING.

**Comment by sctigercat1** [comment]
Are you trying to download from a computer or from cydia?

**Comment by iphoneihelper** [comment]
Cydia. It redirect on repo page with OS X attempt.

You got the no .htaccess part. Logo and proper name appear even the download counter and all. It was never before. Not at least when I have .htaccess in public_html.

**Comment by iphoneihelper** [comment]
Find anything? Its very strange that when I put .htaccess in repo folder its stop working even if the .htaccess also available in public_html folder.

There is something really important remain for .htaccess or its place in order to work properly.

**Comment by iphoneihelper** [comment]
I have only package to host. Is there any possibility to make code work for specific deb name or what best you can suggest if I have only package to host.

Is there any way to check package and release redirect working with method. 

You code is let to add repo to anyone but only selected can download the package, right? There is no restriction on adding repo just only download for particular UDID.

I was trying many things with .htaccess and one time I got SOMEONE SNEAKY showed up. What does that error for?

**Comment by sctigercat1** [comment]
That error is in repfiles.php and shows up when someone tries to download a file that's not supposed to be downloaded.

This repo primarily uses Packages.bz2 and Release, and if a use tries to download a file other than those (plus a few others) it'll show an error to prevent unapproved files from being downloaded.

To test to make sure the htaccess is working at all, you can try deleting all the packages and release files then refreshing your repo from Cydia. If it refreshes successfully, we'll know the htaccess is working because it would have generated new files.

Also, there's something called beta mode which prevents users from adding your repo unless they have a certain permission set (see usergroups.php).

I'm still searching for anything more, but it's a bit difficult to find because I haven't been able to replicate the issue myself.  By deleting the packages and release though, it'll tell us whether or not this is an issue with the htaccess or the deb handing PHP page itself.

**Comment by iphoneihelper** [comment]
As you said the all packages and release files have been deleted.

![img_0861](https://cloud.githubusercontent.com/assets/10158017/6895121/20f04b64-d6fa-11e4-824a-9094abbd8975.png)
1st Case) I have .htaccess file public_html.
-----------------------
RewriteEngine On

RewriteBase /repo/

RewriteRule ^(Packages|Release)(.bz2|.gz|.xz|.lzma|.lz)?$ repofiles.php?request=%{REQUEST_FILENAME}
RewriteRule ^debs/(.*).deb$ repo.php?file=$1 [QSA]
-----------------------
2nd Case)

![img_0862](https://cloud.githubusercontent.com/assets/10158017/6895196/2d0d3776-d6fb-11e4-9c78-bdadc4e0bfab.png)

by moving .htaccess
-----------------------
RewriteEngine On

RewriteBase /

RewriteRule ^(Packages|Release)(.bz2|.gz|.xz|.lzma|.lz)?$ repofiles.php?request=%{REQUEST_FILENAME}
RewriteRule ^debs/(.*).deb$ repo.php?file=$1 [QSA]
-----------------------

**Comment by sctigercat1** [comment]
Okay, so for now keep the second case.

Also, in repofiles.php, comment out lines 194, 196, 197, and 198 for me please (add // to the beginning of the line).

This will disable that error and may allow for Cydia to read the file.

**Comment by iphoneihelper** [comment]
![img_0861](https://cloud.githubusercontent.com/assets/10158017/6895657/0f9441d0-d700-11e4-94b1-603ded2f2364.png)

**Comment by sctigercat1** [comment]
Oh, you can leave those package and release files -- Cydia needs those to refresh the repo, but it's supposed to create them again if they don't exist.

The script has permission to make new files, correct? Because you deleted them they need to be recreated, but a simple refresh is supposed to do it.

Let me know if they don't show back up after a refresh.

**Comment by iphoneihelper** [comment]
I have made little change in .htaccess file.

I have added /repo/ instead of / .... and I refresh Cydia.

Package, Package.bz2 and Release files have been greeted through the script successfully.

Package file contain no information. Plain file.
Release file hold this information.

Origin: My Personal Repo
Label: MyRepo
Suite: stable 
Version: 1.0
Codename: stable
Architectures: darwin-arm 
Components: main 
Description: My Personal UDID Protected Repo!
MD5sum:
 d41d8cd98f00b204e9800998ecf8427e 0 Packages
 4059d198768f9f8dc9372dc1c54bc3c3 14 Packages.bz2

So what is next?

**Comment by sctigercat1** [comment]
Nothing's showing up because the package has permission level 3 and a guest (without a UDID) has permission level 0.

Try adding your UDID in the interface and check if, after a refresh, the package then shows up.

**Comment by iphoneihelper** [comment]
![screenshot 2015-03-30 17 46 15](https://cloud.githubusercontent.com/assets/10158017/6896079/e33bb92e-d704-11e4-9fe9-c9a0d4d27c67.png)


Package holds the information only if the user UDID permission and Package permission information match, right?

For letting the people to download package is by adding permission same as Packages?

Refresh is require in order to work those server changes. Anyone can add repo but only those with UDID can see the package, right?

**Comment by iphoneihelper** [comment]
HTTP/1.1 500 Internal Server Error when I attempt to download the package.

**Comment by sctigercat1** [comment]
Yes, only those with an approved UDID can download the package (and as long as they have an equal or higher user level).  It won't even show up in their package list because it's generated for each person's user level.

As for the 500 error...does it give any more details?

**Comment by iphoneihelper** [comment]
![](http://i.imgur.com/Q0OypKy.jpg)

That's the error.


Everything else I have tried and UDID protection is working fine.

I think it will be fine once this error gone.

**Comment by iphoneihelper** [comment]
One thing I have never mention that MySQL connectivity is not yet done. Does that affect to download package?

I have tried this one also. Set Package permission 0 and UDID permission 0. Still showing same error.

**Comment by iphoneihelper** [comment]
Did try many thing and nothing workout. Do you have any suggestion? I guess is the last issue that we are facing.

**Comment by iphoneihelper** [comment]
Even if I delete deb file its still showing me the same error. Your words might be helpful. What else we could change in code to see where exactly the issue is?

**Comment by sctigercat1** [comment]
Sorry for not responding, this week is a little busy for me.

For the 500 error...it could be the MySQL not being setup.  500 errors aren't the best for debugging issues, so if I had one of these I'd probably just debug the code until I found the error.

Are you able to setup MySQL? If so, try that, but if you didn't want to do, let me know and I'll work on a version without it.

**Comment by iphoneihelper** [comment]
I GOT SOMETHING!

Several Cases

1) I moved the .htaccess to public_html folder and tried to download package. Well of course its started downloading after refresh. Later I change the permission of my UDID to higher than the package. Package.bz2 and Package files should be modify but it did not because there is no .htaccess in folder and as you said before it doesn't locate the file.

2) Copied .htaccess file to public_html/repo folder. We have .htaccess is both directory. I did refresh and work perfect until I tried downloading package. Same 500 internal server error.

Keeping the .htaccess in repo let the UDID, Packages, Package.bz2 to modify punctually on every refresh but throw 500 internal server error while hit install.

Keeping the .htaccess in public_html allow the downloading but if I make any changes to Deb permission or new UDID, it will not reflect and it doesn't  work.

DO YOU FIND ANY SOLUTION FOR THIS?

**Comment by iphoneihelper** [comment]
SOME MORE DETAILS. THIS MIGHT BE RALLY HELPFUL.

Assume the first case. .htaccess in Public_html and UDID modification not taking effect.

I did modify .htaccess file. Packages files are now modifying and UDID protection is working. Next step was install. I realised that as soon as I did those changes that 500 Internal Server Error comes back.

Here's my modified .htaccess file.

RewriteEngine On

RewriteBase /

RewriteRule ^repo/(Packages|Release)(.bz2|.gz|.xz|.lzma|.lz)?$ /repo/repofiles.php?request=%{REQUEST_FILENAME}
RewriteRule ^repo/debs/(.*).deb$ /repo/repo.php?file=$1 [QSA]

-------------------------
I did not setup MySQL.

**Comment by iphoneihelper** [comment]
I understand your busy schedule.

Did you find any way to deal with .htaccess file?

Throws 500 error whenever I have .htaccess file in public_html/repo folder. I did try many things.

Would be really helpful if you give me Non SQL code or just tell me what to comment.

**Comment by iphoneihelper** [comment]
Database was THE issue. Created the database and test all cases and repo is working fine now.

Really appreciate your quality time. Thanks for this code. Have a great day!

**Comment by sctigercat1** [comment]
Ah, glad you got it figured out!

Did you still want the non-mysql code?

**Comment by iphoneihelper** [comment]
No I will just hide the download counter. I want it for myself. Is there any easy way to count to set Zero!

I will also get my hands on repo UI later, actually thats my kinda thing CSS and HTML. (Design) :)

**Comment by sctigercat1** [comment]
I'd probably set the count to 0 in the database, if you have phpmyadmin you can just change the current count to 0, haha.

**Comment by iphoneihelper** [comment]
Thats the only possible thing. What was the switch thing you mention in the README?

Are you implementing any changes currently?

**Comment by sctigercat1** [comment]
Oh yeah, I plan on implementing that soon. I'll put a variable in usergroups.php that'll be something like $UseDownloadCounter and you can set either true or false.

It's not done yet but when it is I'll push it to the repo.

**Comment by finssao** [comment]
hello I also have a problem with my database.  when I enter my UDID and the user level (4) I do not feel that it is sent in the base suddenly I can not add my repo in cydia here is the TUTO that I followed: https://github.com/precisef0x/Cydia-UDID-Protected-Repo-PHP 


can you please help me with this?  thank you for your comeback.  cdt.
